package uman.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_DataType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DataType() {
    super(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4cb86dL, "DataType", "r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867367118957");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_int64_0 = new EnumerationDescriptor.MemberDescriptor("int64", "int64", 0x6dd41c940b4cb86eL, "r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867367118958");
  private final EnumerationDescriptor.MemberDescriptor myMember_string_0 = new EnumerationDescriptor.MemberDescriptor("string", "string", 0x6dd41c940b4cb86fL, "r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867367118959");
  private final EnumerationDescriptor.MemberDescriptor myMember_float_0 = new EnumerationDescriptor.MemberDescriptor("float", "float", 0x6dd41c940b4cb870L, "r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867367118960");
  private final EnumerationDescriptor.MemberDescriptor myMember_boolean_0 = new EnumerationDescriptor.MemberDescriptor("boolean", "boolean", 0x6dd41c940b4cb871L, "r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867367118961");
  private final EnumerationDescriptor.MemberDescriptor myMember_timestamp_0 = new EnumerationDescriptor.MemberDescriptor("timestamp", "timestamp", 0x6dd41c940b4cb872L, "r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867367118962");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4cb86dL, 0x6dd41c940b4cb86eL, 0x6dd41c940b4cb86fL, 0x6dd41c940b4cb870L, 0x6dd41c940b4cb871L, 0x6dd41c940b4cb872L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_int64_0, myMember_string_0, myMember_float_0, myMember_boolean_0, myMember_timestamp_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "int64":
        return myMember_int64_0;
      case "string":
        return myMember_string_0;
      case "float":
        return myMember_float_0;
      case "boolean":
        return myMember_boolean_0;
      case "timestamp":
        return myMember_timestamp_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
