package uman.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptField = createDescriptorForField();
  /*package*/ final ConceptDescriptor myConceptFieldProperties = createDescriptorForFieldProperties();
  /*package*/ final ConceptDescriptor myConceptFieldRefrence = createDescriptorForFieldRefrence();
  /*package*/ final ConceptDescriptor myConceptField_PlaceHolder = createDescriptorForField_PlaceHolder();
  /*package*/ final ConceptDescriptor myConceptModelSchema = createDescriptorForModelSchema();
  /*package*/ final ConceptDescriptor myConceptModels = createDescriptorForModels();
  /*package*/ final ConceptDescriptor myConceptSQL = createDescriptorForSQL();
  /*package*/ final EnumerationDescriptor myEnumerationDataType = new EnumerationDescriptor_DataType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptField, myConceptFieldProperties, myConceptFieldRefrence, myConceptField_PlaceHolder, myConceptModelSchema, myConceptModels, myConceptSQL);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Field:
        return myConceptField;
      case LanguageConceptSwitch.FieldProperties:
        return myConceptFieldProperties;
      case LanguageConceptSwitch.FieldRefrence:
        return myConceptFieldRefrence;
      case LanguageConceptSwitch.Field_PlaceHolder:
        return myConceptField_PlaceHolder;
      case LanguageConceptSwitch.ModelSchema:
        return myConceptModelSchema;
      case LanguageConceptSwitch.Models:
        return myConceptModels;
      case LanguageConceptSwitch.SQL:
        return myConceptSQL;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationDataType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("uman", "Field", 0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8cdL);
    b.class_(false, false, false);
    // extends: uman.structure.Field_PlaceHolder
    b.super_(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4d9b81L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867367114957");
    b.version(3);
    b.property("dataType", 0x6dd41c940b4cb86cL).type(MetaIdFactory.dataTypeId(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4cb86dL)).origin("7913981867367118956").done();
    b.property("Index", 0x6dd41c940b4cbd49L).type(PrimitiveTypeId.BOOLEAN).origin("7913981867367120201").done();
    b.property("Sensitive", 0x6dd41c940b4cbd4aL).type(PrimitiveTypeId.BOOLEAN).origin("7913981867367120202").done();
    b.property("CanBeNull", 0x6dd41c940b6ad1d6L).type(PrimitiveTypeId.BOOLEAN).origin("7913981867369091542").done();
    b.aggregate("rest", 0x6dd41c940b54a901L).target(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b54a902L).optional(true).ordered(true).multiple(true).origin("7913981867367639297").done();
    b.alias("field");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFieldProperties() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("uman", "FieldProperties", 0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b54a902L);
    b.class_(false, true, false);
    b.origin("r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867367639298");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFieldRefrence() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("uman", "FieldRefrence", 0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4cbd4dL);
    b.class_(false, false, false);
    // extends: uman.structure.Field_PlaceHolder
    b.super_(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4d9b81L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867367120205");
    b.version(3);
    b.property("name_of_relation", 0x6dd41c940b4cbd4eL).type(PrimitiveTypeId.STRING).origin("7913981867367120206").done();
    b.property("type_of_relation", 0x6dd41c940b4cbd4fL).type(PrimitiveTypeId.STRING).origin("7913981867367120207").done();
    b.associate("target_schema", 0x6dd41c940b4cbd51L).target(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8c9L).optional(false).origin("7913981867367120209").done();
    b.alias("relation");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForField_PlaceHolder() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("uman", "Field_PlaceHolder", 0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4d9b81L);
    b.class_(false, true, false);
    b.origin("r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867367177089");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModelSchema() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("uman", "ModelSchema", 0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8c9L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867367114953");
    b.version(3);
    b.aggregate("Fields", 0x6dd41c940b4ca8ccL).target(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4d9b81L).optional(false).ordered(true).multiple(true).origin("7913981867367114956").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModels() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("uman", "Models", 0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8c6L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867367114950");
    b.version(3);
    b.aggregate("schemas", 0x6dd41c940b4ca8c8L).target(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8c9L).optional(false).ordered(true).multiple(true).origin("7913981867367114952").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSQL() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("uman", "SQL", 0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b625dc7L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:22b0f938-2771-480c-8e65-411380d57efc(uman.structure)/7913981867368537543");
    b.version(3);
    b.associate("targetScemaFilde", 0x6dd41c940b625dc8L).target(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8c6L).optional(false).origin("7913981867368537544").done();
    return b.create();
  }
}
