package uman.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import uman.behavior.Schema__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import uman.behavior.Field__BehaviorDescriptor;
import jetbrains.mps.internal.collections.runtime.Sequence;
import uman.behavior.FieldRefrence__BehaviorDescriptor;
import jetbrains.mps.baseLanguage.closures.runtime.Wrappers;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;

public class Code_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    SNode n = ctx.getPrimaryInput();
    SNode models = SLinkOperations.getTarget(n, LINKS.models$9yIw);
    SNode infra = SLinkOperations.getTarget(n, LINKS.infra$9yXx);

    tgs.append("package main\n\nimport (\n\t\"database/sql\"\n\t_ \"embed\"\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"log\"\n\t\"net/http\"\n\t\"os\"\n\t\"strconv\"\n\t\"time\"\n\n\t_ \"github.com/lib/pq\"\n\thttpSwagger \"github.com/swaggo/http-swagger\"\n\t_ \"");
    tgs.append(SPropertyOperations.getString(infra, PROPS.modulePath$Ruex));
    tgs.append("/docs\"\n)\n\n//go:embed user_management_init.sql\nvar migrationSQL string\n\n// @title         ");
    tgs.append(SPropertyOperations.getString(models, PROPS.name$MnvL));
    tgs.append(" API\n// @version       1.0\n// @description   CRUD service for ");
    tgs.append(SPropertyOperations.getString(models, PROPS.name$MnvL));
    tgs.append("\n// @host          localhost:");
    tgs.append(SPropertyOperations.getInteger(infra, PROPS.port$RtZw) + "");
    tgs.append("\n// @BasePath      /\n// @schemes       http\n// @produce       json\n// @consumes      json\n\n// ============================================================\n// Models\n// ============================================================\n\n");

    // // ---- Regular schema structs ----

    for (SNode schema : ListSequence.fromList(SLinkOperations.getChildren(models, LINKS.schemas$wVBY))) {
      if (!((boolean) Schema__BehaviorDescriptor.hasReferences_id4RkLmywWXpy.invoke(schema))) {
        tgs.append("type ");
        tgs.append(Schema__BehaviorDescriptor.structName_id4RkLmywWSH4.invoke(schema));
        tgs.append(" struct ");
        tgs.append("\n\tID int64 `json:\"id\" db:\"id\" example:\"1\"`\n");
        for (SNode field : ListSequence.fromList(SLinkOperations.getChildren(schema, LINKS.Fields$wW_v))) {
          {
            final SNode f = field;
            if (SNodeOperations.isInstanceOf(f, CONCEPTS.Field$YI)) {
              tgs.append("\t");
              tgs.append(Field__BehaviorDescriptor.pascalCase_id4TZlN6tfVyQ.invoke(f, SPropertyOperations.getString(f, PROPS.name$MnvL)));
              tgs.append(" ");
              tgs.append(Field__BehaviorDescriptor.goType_id4RkLmywX45R.invoke(f));
              tgs.append(" `json:\"");
              tgs.append(SPropertyOperations.getString(f, PROPS.name$MnvL));
              tgs.append("\" db:\"");
              tgs.append(SPropertyOperations.getString(f, PROPS.name$MnvL));
              tgs.append("\"`\n");
            }
          }
        }
        tgs.append("}\n\n");
        // marshal jason
        boolean hasSensitive = Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(schema, LINKS.Fields$wW_v), CONCEPTS.Field$YI)).any((it) -> SPropertyOperations.getBoolean(it, PROPS.Sensitive$cq$U));

        if (hasSensitive) {
          tgs.append("func (u ");
          tgs.append(Schema__BehaviorDescriptor.structName_id4RkLmywWSH4.invoke(schema));
          tgs.append(") MarshalJSON() ([]byte, error) {\n\ttype Alias ");
          tgs.append(Schema__BehaviorDescriptor.structName_id4RkLmywWSH4.invoke(schema));
          tgs.append("\n\treturn json.Marshal(&struct {\n\t\tAlias\n");
          ListSequence.fromList(SLinkOperations.getChildren(schema, LINKS.Fields$wW_v)).visitAll((it) -> {
            {
              final SNode f = it;
              if (SNodeOperations.isInstanceOf(f, CONCEPTS.Field$YI)) {
                if (SPropertyOperations.getBoolean(f, PROPS.Sensitive$cq$U)) {
                  // appen  {\t\t} ${f.pascalName()} { string `json:"} ${f.name} {"`\n} ;
                  tgs.append("\t\t");
                  tgs.append(Field__BehaviorDescriptor.pascalName_id4TZlN6thmic.invoke(f));
                  tgs.append(" string `json:\"");
                  tgs.append(SPropertyOperations.getString(f, PROPS.name$MnvL));
                  tgs.append("\"`\n");
                }
              }
            }
          });
          tgs.append("\t");
          tgs.append("\n\t\tAlias: (Alias)(u),\n");
          Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(schema, LINKS.Fields$wW_v), CONCEPTS.Field$YI)).visitAll((it) -> {
            if (SPropertyOperations.getBoolean(it, PROPS.Sensitive$cq$U)) {
              tgs.append("\t\t");
              tgs.append(Field__BehaviorDescriptor.pascalName_id4TZlN6thmic.invoke(it));
              tgs.append(": \"[REDACTED]\",\n");
            }
          });
          tgs.append("\t");
          tgs.append("})\n");
          tgs.append("}\n\n");
        }
        // Create struct
        tgs.append("type ");
        tgs.append(Schema__BehaviorDescriptor.CreateStructName_id4RkLmywWW1l.invoke(schema));
        tgs.append(" struct {\n");
        Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(schema, LINKS.Fields$wW_v), CONCEPTS.Field$YI)).where((it) -> SPropertyOperations.getEnum(it, PROPS.dataType$lMLn).getPresentation().equals("timestamp")).visitAll((it) -> {
          {
            SNode f = it;
            tgs.append("\t");
            tgs.append(Field__BehaviorDescriptor.pascalName_id4TZlN6thmic.invoke(f));
            tgs.append(" ");
            tgs.append(Field__BehaviorDescriptor.goType_id4RkLmywX45R.invoke(f));
            tgs.append(" `json:\"");
            tgs.append(SPropertyOperations.getString(f, PROPS.name$MnvL));
            tgs.append("\"`\n");
          }
        });
        tgs.append("}\n\n");
      }
    }

    // ---- Join schema structs ----

    for (SNode sch : ListSequence.fromList(SLinkOperations.getChildren(models, LINKS.schemas$wVBY))) {
      if ((boolean) Schema__BehaviorDescriptor.hasReferences_id4RkLmywWXpy.invoke(sch)) {
        tgs.append("type ");
        tgs.append(Schema__BehaviorDescriptor.structName_id4RkLmywWSH4.invoke(sch));
        tgs.append(" struct {\n");

        ListSequence.fromList(SLinkOperations.getChildren(sch, LINKS.Fields$wW_v)).visitAll((it) -> {
          {
            final SNode fr = it;
            if (SNodeOperations.isInstanceOf(fr, CONCEPTS.FieldRefrence$yH)) {
              tgs.append("\t");
              tgs.append(FieldRefrence__BehaviorDescriptor.pascalName_id4RkLmywXs7j.invoke(fr));
              tgs.append(" int64 `json:\"");
              tgs.append(SPropertyOperations.getString(fr, PROPS.name$MnvL));
              tgs.append("\" db:\"");
              tgs.append(SPropertyOperations.getString(fr, PROPS.name$MnvL));
              tgs.append("\"`\n");
            }
          }
          {
            final SNode f = it;
            if (SNodeOperations.isInstanceOf(f, CONCEPTS.Field$YI)) {
              tgs.append("\t");
              tgs.append(Field__BehaviorDescriptor.pascalName_id4TZlN6thmic.invoke(f));
              tgs.append(" ");
              tgs.append(Field__BehaviorDescriptor.goType_id4RkLmywX45R.invoke(f));
              tgs.append(" `json:\"");
              tgs.append(SPropertyOperations.getString(f, PROPS.name$MnvL));
              tgs.append("\" db:\"");
              tgs.append(SPropertyOperations.getString(f, PROPS.name$MnvL));
              tgs.append("\"`\n");
            }
          }
        });
        tgs.append("}\n\n");
        final Wrappers._int refC = new Wrappers._int(0);
        Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(sch, LINKS.Fields$wW_v), CONCEPTS.FieldRefrence$yH)).visitAll((it) -> {
          if (refC.value == 1) {
            tgs.append("type Assign");
            tgs.append(Schema__BehaviorDescriptor.structName_id4RkLmywWSH4.invoke(SLinkOperations.getTarget(it, LINKS.target_schema$EJM0)));
            tgs.append("Body struct {\n\t");
            tgs.append(FieldRefrence__BehaviorDescriptor.pascalName_id4RkLmywXs7j.invoke(it));
            tgs.append(" int64 `json:\"");
            tgs.append(SPropertyOperations.getString(it, PROPS.name$MnvL));
            tgs.append("\" binding:\"required\"`\n}\n\n");
          }
          refC.value++;
        });
      }
    }


    // ============================================================
    // Repositories — regular
    // ============================================================

    tgs.append("// ============================================================\n// Repositories\n// ============================================================\n\n");
    for (SNode sc : ListSequence.fromList(SLinkOperations.getChildren(models, LINKS.schemas$wVBY))) {
      if (!((boolean) Schema__BehaviorDescriptor.hasReferences_id4RkLmywWXpy.invoke(sc))) {
        String sn = Schema__BehaviorDescriptor.structName_id4RkLmywWSH4.invoke(sc);
        String rn = Schema__BehaviorDescriptor.repoName_id4RkLmywWUlE.invoke(sc);
        String tn = SPropertyOperations.getString(sc, PROPS.name$MnvL);

        tgs.append("type ");
        tgs.append(rn);
        tgs.append(" struct{ db *sql.DB }\n\n");

        // Create
        tgs.append("func (r *");
        tgs.append(rn);
        tgs.append(") Create(u *");
        tgs.append(sn);
        tgs.append(") error {\n\treturn r.db.QueryRow(\n\t\t`INSERT INTO ");
        tgs.append(tn);
        tgs.append(" (");
        final Wrappers._int idx = new Wrappers._int(0);
        Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(sc, LINKS.Fields$wW_v), CONCEPTS.Field$YI)).visitAll((it) -> {
          if (!(SPropertyOperations.getEnum(it, PROPS.dataType$lMLn).getPresentation().equals("timestamp"))) {
            if (idx.value > 0) {
              tgs.append(", ");
            }
            tgs.append(SPropertyOperations.getString(it, PROPS.name$MnvL));
            idx.value++;
          }

        });
        tgs.append(")\n\t\t VALUES (");
        for (int i = 1; i <= idx.value; i++) {
          if (i > 1) {
            tgs.append(", ");
          }
          tgs.append("$");
          tgs.append("i");
        }
        tgs.append(")\n\t\t RETURNING id");
        Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(sc, LINKS.Fields$wW_v), CONCEPTS.Field$YI)).visitAll((it) -> {
          if (SPropertyOperations.getEnum(it, PROPS.dataType$lMLn).getPresentation().equals("timestamp")) {
            tgs.append(", ");
            tgs.append(SPropertyOperations.getString(it, PROPS.name$MnvL));
          }
        });
        tgs.append("`,\n");
        // non timestapm
        Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(sc, LINKS.Fields$wW_v), CONCEPTS.Field$YI)).where((it) -> !(SPropertyOperations.getEnum(it, PROPS.dataType$lMLn).getPresentation().equals("timestamp"))).visitAll((it) -> {
          // append {\t\tu.} ${f.pascalName()} {,\n} ;
          tgs.append("\t\tu.");
          tgs.append(Field__BehaviorDescriptor.pascalName_id4TZlN6thmic.invoke(it));
          tgs.append(",\n");
        });

        // scanning

        tgs.append("\t).Scan(&u.ID");
        Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(sc, LINKS.Fields$wW_v), CONCEPTS.Field$YI)).where((it) -> SPropertyOperations.getEnum(it, PROPS.dataType$lMLn).getPresentation().equals("timestamp")).visitAll((it) -> {
          tgs.append(", &u.");
          tgs.append(Field__BehaviorDescriptor.pascalName_id4TZlN6thmic.invoke(it));
        });
        tgs.append(")\n}\n\n");

        // GetByID

        tgs.append("func (r *");
        tgs.append(rn);
        tgs.append(") GetByID(id int64) (*");
        tgs.append(sn);
        tgs.append(", error) {\n\tu := &");
        tgs.append(sn);
        tgs.append("{}\n\terr := r.db.QueryRow(\n\t\t`SELECT id");
        Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(sc, LINKS.Fields$wW_v), CONCEPTS.Field$YI)).visitAll((it) -> {

          tgs.append(", ");
          tgs.append(SPropertyOperations.getString(it, PROPS.name$MnvL));
        });
        tgs.append("\n\t\t FROM ");
        tgs.append(tn);
        tgs.append(" WHERE id = $1`, id,\n\t).Scan(&u.ID");
        Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(sc, LINKS.Fields$wW_v), CONCEPTS.Field$YI)).visitAll((it) -> {
          tgs.append(", &u.");
          tgs.append(Field__BehaviorDescriptor.pascalName_id4TZlN6thmic.invoke(it));
        });
        tgs.append(")\n\treturn u, err\n}\n\n");

        // List
        tgs.append("func (r *");
        tgs.append(rn);
        tgs.append(") List() ([]");
        tgs.append(sn);
        tgs.append(", error) {\n\trows, err := r.db.Query(\n\t\t`SELECT id");
        Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(sc, LINKS.Fields$wW_v), CONCEPTS.Field$YI)).visitAll((it) -> {
          tgs.append(", ");
          tgs.append(Field__BehaviorDescriptor.pascalName_id4TZlN6thmic.invoke(it));
        });
        tgs.append("\n\t\t FROM ");
        tgs.append(tn);
        tgs.append(" ORDER BY id`)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tdefer rows.Close()\n\tvar items []");
        tgs.append(sn);
        tgs.append("\n\tfor rows.Next() {\n\t\tvar u ");
        tgs.append(sn);
        tgs.append("\n\t\tif err := rows.Scan(&u.ID");
        Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(sc, LINKS.Fields$wW_v), CONCEPTS.Field$YI)).visitAll((it) -> {
          tgs.append(", &u.");
          tgs.append(Field__BehaviorDescriptor.pascalName_id4TZlN6thmic.invoke(it));
        });
        tgs.append("); err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t\titems = append(items, u)\n\t}\n\treturn items, rows.Err()\n}\n\n");

        // Update
        tgs.append("func (r *");
        tgs.append(rn);
        tgs.append(") Update(u *");
        tgs.append(sn);
        tgs.append(") error {\n\treturn r.db.QueryRow(\n\t\t`UPDATE ");
        tgs.append(tn);
        tgs.append(" SET ");
        final Wrappers._int uidx = new Wrappers._int(0);
        Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(sc, LINKS.Fields$wW_v), CONCEPTS.Field$YI)).where((it) -> !(SPropertyOperations.getEnum(it, PROPS.dataType$lMLn).getPresentation().equals("timestamp"))).visitAll((it) -> {
          if (uidx.value > 0) {
            tgs.append(", ");
          }
          uidx.value++;
          tgs.append(SPropertyOperations.getString(it, PROPS.name$MnvL));
          tgs.append(" = $");
          tgs.append(uidx.value + "");
        });

        tgs.append("\t\tu.ID,\n\t).Scan(&u.UpdatedAt)\n}\n\n");

        // Delete
        tgs.append("func (r *");
        tgs.append(rn);
        tgs.append(") Delete(id int64) error {\n\t_, err := r.db.Exec(`DELETE FROM } ${tn} { WHERE id = $1`, id)\n\treturn err\n}\n\n");
      }
    }

    // ============================================================
    // Repositories — join schemas
    // ============================================================





















  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink models$9yIw = MetaAdapterFactory.getReferenceLink(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x4dd4c568a0f090c5L, 0x4dd4c568a0f090c9L, "models");
    /*package*/ static final SReferenceLink infra$9yXx = MetaAdapterFactory.getReferenceLink(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x4dd4c568a0f090c5L, 0x4dd4c568a0f090caL, "infra");
    /*package*/ static final SContainmentLink Fields$wW_v = MetaAdapterFactory.getContainmentLink(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8c9L, 0x6dd41c940b4ca8ccL, "Fields");
    /*package*/ static final SContainmentLink schemas$wVBY = MetaAdapterFactory.getContainmentLink(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8c6L, 0x6dd41c940b4ca8c8L, "schemas");
    /*package*/ static final SReferenceLink target_schema$EJM0 = MetaAdapterFactory.getReferenceLink(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4cbd4dL, 0x6dd41c940b4cbd51L, "target_schema");
  }

  private static final class PROPS {
    /*package*/ static final SProperty modulePath$Ruex = MetaAdapterFactory.getProperty(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x4dd4c568a0f090cbL, 0x4dd4c568a0f2d70aL, "modulePath");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty port$RtZw = MetaAdapterFactory.getProperty(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x4dd4c568a0f090cbL, 0x4dd4c568a0f2d709L, "port");
    /*package*/ static final SProperty Sensitive$cq$U = MetaAdapterFactory.getProperty(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8cdL, 0x6dd41c940b4cbd4aL, "Sensitive");
    /*package*/ static final SProperty dataType$lMLn = MetaAdapterFactory.getProperty(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8cdL, 0x6dd41c940b4cb86cL, "dataType");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Field$YI = MetaAdapterFactory.getConcept(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8cdL, "uman.structure.Field");
    /*package*/ static final SConcept FieldRefrence$yH = MetaAdapterFactory.getConcept(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4cbd4dL, "uman.structure.FieldRefrence");
  }
}
