package uman.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;

public class SQL_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    SNode n = ctx.getPrimaryInput();
    tgs.append("CREATE TABLE IF NOT EXISTS ");
    tgs.append("_users_");
    tgs.append(" (\n");
    tgs.append("    ");
    tgs.append("id");
    tgs.append("            BIGSERIAL       PRIMARY KEY,\n");
    tgs.append("    ");
    tgs.append("_username_");
    tgs.append("      TEXT            NOT NULL UNIQUE,\n");
    tgs.append("    ");
    tgs.append("_email_");
    tgs.append("         TEXT            NOT NULL UNIQUE,\n");

    tgs.append("    ");
    tgs.append("_password_");
    tgs.append("       TEXT            NOT NULL,\n");
    tgs.append("    ");
    tgs.append("_first_name_");
    tgs.append("    TEXT            NOT NULL DEFAULT '',\n");
    tgs.append("    ");
    tgs.append("_last_name_");
    tgs.append("     TEXT            NOT NULL DEFAULT '',\n");
    tgs.append("    ");
    tgs.append("_is_active_");
    tgs.append("     BOOLEAN         NOT NULL DEFAULT true,\n");
    tgs.append("    ");
    tgs.append("_created_at_");
    tgs.append("    TIMESTAMPTZ     NOT NULL DEFAULT NOW(),\n");
    tgs.append("    ");
    tgs.append("_updated_at_");
    tgs.append("    TIMESTAMPTZ     NOT NULL DEFAULT NOW()");
    tgs.append("\n);\n");


    tgs.append("CREATE TABLE IF NOT EXISTS ");
    tgs.append("_roles_");
    tgs.append(" (\n");
    tgs.append("    ");
    tgs.append("id");
    tgs.append("            BIGSERIAL       PRIMARY KEY,\n");
    tgs.append("    ");
    tgs.append("_name_");
    tgs.append("          TEXT            NOT NULL UNIQUE,\n");
    tgs.append("    ");
    tgs.append("_description_");
    tgs.append("   TEXT            NOT NULL DEFAULT '',\n");
    tgs.append("    ");
    tgs.append("_created_at_");
    tgs.append("    TIMESTAMPTZ     NOT NULL DEFAULT NOW()\n");
    tgs.append(");\n");


    tgs.append("CREATE TABLE IF NOT EXISTS ");
    tgs.append("_user_roles_");
    tgs.append(" (\n");
    tgs.append(");\n");

  }
}
