package uman.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import uman.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.SQL:
        return new SQL_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.SQL$Ip)) {
        String fname = getFileName_SQL(root);
        String ext = getFileExtension_SQL(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), getPath_SQL(root), root);
        continue;
      }
    }
  }
  private static String getFileName_SQL(SNode node) {
    return "user_management_sql";
  }
  private static String getFileExtension_SQL(SNode node) {
    return "sql";
  }
  private static String getPath_SQL(SNode node) {
    return "sql/";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept SQL$Ip = MetaAdapterFactory.getConcept(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b625dc7L, "uman.structure.SQL");
  }
}
