package uman.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import org.jetbrains.mps.openapi.language.SProperty;

public final class Field__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8cdL, "uman.structure.Field");

  public static final SMethod<String> goType_id4RkLmywX45R = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("goType").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5608324489150742903L).languageId(0xa4526f9ea85ed21fL, 0x1347621f0e534de9L).build2();
  public static final SMethod<String> pascalCase_id4TZlN6tfVyQ = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("pascalCase").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5656335527603845302L).languageId(0xa4526f9ea85ed21fL, 0x1347621f0e534de9L).build2(SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<String> pascalName_id4TZlN6thmic = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("pascalName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5656335527604216972L).languageId(0xa4526f9ea85ed21fL, 0x1347621f0e534de9L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(goType_id4RkLmywX45R, pascalCase_id4TZlN6tfVyQ, pascalName_id4TZlN6thmic);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String goType_id4RkLmywX45R(@NotNull SNode __thisNode__) {

    String dataTypeString;
    switch (enumSwitchIndex.indexNullable(SPropertyOperations.getEnum(__thisNode__, PROPS.dataType$lMLn))) {
      case 0:
        dataTypeString = "bool";
        break;
      case 1:
        dataTypeString = "float";
        break;
      case 2:
        dataTypeString = "int64";
        break;
      case 3:
        dataTypeString = "string";
        break;
      case 4:
        dataTypeString = "timestamp";
        break;
      default:
        dataTypeString = "interface{}";
        break;
    }
    return dataTypeString;
  }
  /*package*/ static String pascalCase_id4TZlN6tfVyQ(@NotNull SNode __thisNode__, String inpt) {
    StringBuilder sb = new StringBuilder();
    String[] parts = inpt.split("_");
    for (int i = 0; i < parts.length; i++) {
      String part = parts[i];
      if (part.length() > 0) {
        sb.append(part.substring(0, 1).toUpperCase());
        if (part.length() > 1) {
          sb.append(part.substring(1));
        }
      }
    }
    return sb.toString();

  }
  /*package*/ static String pascalName_id4TZlN6thmic(@NotNull SNode __thisNode__) {
    return ((String) Field__BehaviorDescriptor.pascalCase_id4TZlN6tfVyQ.invoke(__thisNode__, SPropertyOperations.getString(__thisNode__, PROPS.name$MnvL)));
  }

  /*package*/ Field__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) goType_id4RkLmywX45R(node));
      case 1:
        return (T) ((String) pascalCase_id4TZlN6tfVyQ(node, (String) parameters[0]));
      case 2:
        return (T) ((String) pascalName_id4TZlN6thmic(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }
  private static final EnumerationLiteralsIndex enumSwitchIndex = EnumerationLiteralsIndex.build(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4cb86dL, 0x6dd41c940b4cb871L, 0x6dd41c940b4cb870L, 0x6dd41c940b4cb86eL, 0x6dd41c940b4cb86fL, 0x6dd41c940b4cb872L);

  private static final class PROPS {
    /*package*/ static final SProperty dataType$lMLn = MetaAdapterFactory.getProperty(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8cdL, 0x6dd41c940b4cb86cL, "dataType");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
