package uman.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public final class Schema__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8c9L, "uman.structure.Schema");

  public static final SMethod<String> pascalCase_id4RkLmywWHtP = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("pascalCase").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5608324489150650229L).languageId(0xa4526f9ea85ed21fL, 0x1347621f0e534de9L).build2(SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<String> singularName_id4RkLmywWNem = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("singularName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5608324489150673814L).languageId(0xa4526f9ea85ed21fL, 0x1347621f0e534de9L).build2();
  public static final SMethod<String> structName_id4RkLmywWSH4 = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("structName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5608324489150696260L).languageId(0xa4526f9ea85ed21fL, 0x1347621f0e534de9L).build2();
  public static final SMethod<String> repoName_id4RkLmywWUlE = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("repoName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5608324489150702954L).languageId(0xa4526f9ea85ed21fL, 0x1347621f0e534de9L).build2();
  public static final SMethod<String> CreateStructName_id4RkLmywWW1l = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("CreateStructName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5608324489150709845L).languageId(0xa4526f9ea85ed21fL, 0x1347621f0e534de9L).build2();
  public static final SMethod<Boolean> hasReferences_id4RkLmywWXpy = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("hasReferences").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5608324489150715490L).languageId(0xa4526f9ea85ed21fL, 0x1347621f0e534de9L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(pascalCase_id4RkLmywWHtP, singularName_id4RkLmywWNem, structName_id4RkLmywWSH4, repoName_id4RkLmywWUlE, CreateStructName_id4RkLmywWW1l, hasReferences_id4RkLmywWXpy);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String pascalCase_id4RkLmywWHtP(@NotNull SNode __thisNode__, String inpt) {
    StringBuilder sb = new StringBuilder();
    String[] parts = inpt.split("_");
    for (int i = 0; i < parts.length; i++) {
      String part = parts[i];
      if (part.length() > 0) {
        sb.append(part.substring(0, 1).toUpperCase());
        if (part.length() > 1) {
          sb.append(part.substring(1));
        }
      }
    }
    return sb.toString();

  }
  /*package*/ static String singularName_id4RkLmywWNem(@NotNull SNode __thisNode__) {
    SNode me = __thisNode__;
    String name = SPropertyOperations.getString(me, PROPS.name$MnvL);
    if (name.endsWith("s") && name.length() > 1) {
      return name.substring(0, name.length() - 1);
    }
    return name;

  }
  /*package*/ static String structName_id4RkLmywWSH4(@NotNull SNode __thisNode__) {
    return ((String) Schema__BehaviorDescriptor.pascalCase_id4RkLmywWHtP.invoke(__thisNode__, Schema__BehaviorDescriptor.singularName_id4RkLmywWNem.invoke(__thisNode__)));
  }
  /*package*/ static String repoName_id4RkLmywWUlE(@NotNull SNode __thisNode__) {
    return Schema__BehaviorDescriptor.structName_id4RkLmywWSH4.invoke(__thisNode__) + "Repo";
  }
  /*package*/ static String CreateStructName_id4RkLmywWW1l(@NotNull SNode __thisNode__) {
    return Schema__BehaviorDescriptor.structName_id4RkLmywWSH4.invoke(__thisNode__) + "Create";
  }
  /*package*/ static boolean hasReferences_id4RkLmywWXpy(@NotNull SNode __thisNode__) {
    for (SNode f : ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.Fields$wW_v))) {
      if (SNodeOperations.isInstanceOf(f, CONCEPTS.FieldRefrence$yH)) {
        return true;
      }
    }
    return false;
  }

  /*package*/ Schema__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) pascalCase_id4RkLmywWHtP(node, (String) parameters[0]));
      case 1:
        return (T) ((String) singularName_id4RkLmywWNem(node));
      case 2:
        return (T) ((String) structName_id4RkLmywWSH4(node));
      case 3:
        return (T) ((String) repoName_id4RkLmywWUlE(node));
      case 4:
        return (T) ((String) CreateStructName_id4RkLmywWW1l(node));
      case 5:
        return (T) ((Boolean) hasReferences_id4RkLmywWXpy(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FieldRefrence$yH = MetaAdapterFactory.getConcept(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4cbd4dL, "uman.structure.FieldRefrence");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink Fields$wW_v = MetaAdapterFactory.getContainmentLink(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8c9L, 0x6dd41c940b4ca8ccL, "Fields");
  }
}
