package uman.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.ConstraintFunction;
import jetbrains.mps.smodel.runtime.ConstraintContext_CanBeChild;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SProperty;

public class FieldRefrence_Constraints extends BaseConstraintsDescriptor {
  /*package*/ FieldRefrence_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.FieldRefrence$yH, initContext);
    setCanBeChildConstraint(new ConstraintFunction<ConstraintContext_CanBeChild, Boolean>() {
      @NotNull
      public Boolean invoke(@NotNull ConstraintContext_CanBeChild context, @Nullable CheckingNodeContext checkingNodeContext) {
        boolean result = staticCanBeAChild(context.getNode(), context.getParentNode(), context.getConcept(), context.getLink());

        if (!(result) && checkingNodeContext != null) {
          checkingNodeContext.setBreakingNode(canBeChildBreakingPoint);
        }

        return result;
      }
    });
  }

  private static boolean staticCanBeAChild(SNode node, SNode parentNode, SAbstractConcept childConcept, SContainmentLink link) {
    boolean allow = false;

    {
      final SNode schema = parentNode;
      if (SNodeOperations.isInstanceOf(schema, CONCEPTS.Schema$WM)) {
        allow = SPropertyOperations.getString(schema, PROPS.name$MnvL) != SPropertyOperations.getString(SLinkOperations.getTarget(node, LINKS.target_schema$EJM0), PROPS.name$MnvL);
      }
    }
    return allow;
  }
  private static final SNodePointer canBeChildBreakingPoint = new SNodePointer("r:d5a1c46f-39d0-4886-95dd-cb0bab44a512(uman.constraints)", "7913981867370570269");

  private static final class CONCEPTS {
    /*package*/ static final SConcept FieldRefrence$yH = MetaAdapterFactory.getConcept(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4cbd4dL, "uman.structure.FieldRefrence");
    /*package*/ static final SConcept Schema$WM = MetaAdapterFactory.getConcept(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4ca8c9L, "uman.structure.Schema");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink target_schema$EJM0 = MetaAdapterFactory.getReferenceLink(0x1347621f0e534de9L, 0xa4526f9ea85ed21fL, 0x6dd41c940b4cbd4dL, 0x6dd41c940b4cbd51L, "target_schema");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
